#!/bin/sh
## cut_mail for  in /home/samy.aitouakli/rendu/SHL_2016_shell
## 
## Made by Samy Aitouakli
## Login   <samy.aitouakli@epitech.net>
## 
## Started on  Mon Jan  2 17:30:31 2017 Samy Aitouakli
## Last update Tue Jan  3 21:37:51 2017 Alexis Zeghers
##

file=$1;
i=0;
new_file="/dev/null"
if [ $# -ne 2 ]
then
    echo "USAGE: $0 mbox destdir" >&2
    exit 1;
fi
mkdir -p $2
while read -r line
do
    if [[ $line =~ ^"From " ]]
    then
	i=$(($i + 1));
	new_file=$2/$i.mail;
	touch $new_file;
    fi;
    echo $line >> $new_file
done <"$file";
if [ $new_file == "/dev/null" ]
then
    exit 1;
fi
echo "$i mail found"
exit 0;
