#!/bin/sh
## killall for  in /home/samy.aitouakli/rendu/SHL_2016_shell
## 
## Made by Samy Aitouakli
## Login   <samy.aitouakli@epitech.net>
## 
## Started on  Tue Jan  3 16:21:53 2017 Samy Aitouakli
## Last update Tue Jan  3 23:34:22 2017 Alexis Zeghers
##

function usage()
{
    echo "USAGE: $0 option" >&2
    echo "option: -user user1 ... : Kill all processes for user1, ..." >&2
    echo -e "\t-pid pid1 ... : Kill a process with pid pid1, ..." >&2
    echo -e "\t-prog prog1 ... : Kill all processes whose program's name is prog1, ..." >&2
    echo -e "\t-all : Kill all processes" >&2
    exit 1;
}

function user()
{
    error=-1;
    for i in "$@"
    do
	if [ $i != "-user" ]
	then
	    kill `ps -U $i -f | tr -s ' ' | tail -n +2 | cut -d' ' -f2` > /dev/null
	    [ $? -eq 1 ] && error=$(($error+1));
	fi
    done
    [ $error -gt 0 ] && exit 1;
    echo "[...]"
    exit 0;
}

function pid()
{
    error=0;
    for i in "$@"
    do
	if [ $i != "-pid" ]
	then
	    kill $i > /dev/null
	    [ $? -eq 1 ] && error=1;
	fi
    done
    [ $error -eq 1 ] && exit 1;
    echo "[...]"
    exit 0
}

function prog()
{
    error=0;
    for i in "$@"
    do
	if [ $i != "-prog" ]
	then
	    kill `ps -ef | tr -s ' ' | grep $i | head -n -1 | cut -d' ' -f2` > /dev/null
	    [ $? -eq 1 ] && error=1;
	fi
    done
    [ $error -eq 1 ] && exit 1;
    echo "[...]"
    exit 0;
}

function all()
{
    error=0;
    kill `ps -ef | tr -s ' ' | tail -n +2 | cut -d' ' -f2` > /dev/null
    [ $? -eq 1 ] && error=1;
    [ $error -eq 1 ] && exit 1;
    echo "[...]"
    exit 0;
}
[ $# -eq 0 ] && usage;
if [[ $# -eq 1 && $1 == "-all" ]]
then
    all $@
elif [ $# -eq 1 ]
then
    usage
fi
[ $1 == "-user" ] && user $@
[ $1 == "-pid" ] && pid $@
[ $1 == "-prog" ] && prog $@
usage
